import type { Metadata } from "next";
import { Geist, Geist_Mono, Great_Vibes } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local';

const greatVibes = Great_Vibes({
  weight: ['400'],
  variable: "--font-great_vibes",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// Подключаем локальные шрифты
const publicSans = localFont({
  src: [
    {
      path: '../public/fonts/PublicSans-Thin.ttf',
      weight: '100',
      style: 'normal',
    },
    {
      path: '../public/fonts/PublicSans-ExtraLight.ttf',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../public/fonts/PublicSans-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/PublicSans-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/PublicSans-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/PublicSans-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/PublicSans-Black.ttf',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-public-sans',
});

const playfairDisplay = localFont({
  src: [
    {
      path: '../public/fonts/PlayfairDisplay-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/PlayfairDisplay-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/PlayfairDisplay-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/PlayfairDisplay-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-playfair-display',
});

// const greatVibes = localFont({
//   src: '../public/fonts/GreatVibes-Regular.ttf',
//   weight: '400',
//   variable: '--font-great-vibes',
// });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ${geistSans.variable} ${geistMono.variable}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`
      ${greatVibes.variable}
      ${publicSans.variable} ${playfairDisplay.variable} ${greatVibes.variable}`}>
        {children}
      </body>
    </html>
  );
}
